// Customizer const
export const TOGGLE_COLLAPSED_NAV = 'TOGGLE_COLLAPSE_MENU';
export const WINDOW_WIDTH = 'WINDOW-WIDTH';
export const SWITCH_LANGUAGE = 'SWITCH-LANGUAGE';

// Auth const
export const AUTH_USER_INFO = 'AUTH_USER_INFO';

// Customizer const
export const THEME_TYPE = 'THEME_TYPE';
export const THEME_TYPE_SEMI_DARK = 'THEME_TYPE_SEMI_DARK';
export const THEME_COLOR = 'THEME_COLOR';
export const NAV_STYLE_MINI = 'NAV_STYLE_MINI';
export const LAYOUT_TYPE = 'LAYOUT_TYPE';
export const LAYOUT_TYPE_FULL = 'LAYOUT_TYPE_FULL';
export const NAV_STYLE = 'NAV_STYLE';
export const NAV_STYLE_FIXED = 'NAV_STYLE_FIXED';
export const NAV_STYLE_MINI_SIDEBAR = 'NAV_STYLE_MINI_SIDEBAR';
export const NAV_STYLE_DRAWER = 'NAV_STYLE_DRAWER';
export const NAV_STYLE_NO_HEADER_MINI_SIDEBAR =
    'NAV_STYLE_NO_HEADER_MINI_SIDEBAR';
export const NAV_STYLE_NO_HEADER_EXPANDED_SIDEBAR =
    'NAV_STYLE_NO_HEADER_EXPANDED_SIDEBAR';
export const TAB_SIZE = 992;

// Persist setting ActionType
export const AUTH_PERMISSION_DENIED_401 = 'AUTH_PERMISSION_DENIED_401';
